version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      # Managed by Expo:
      - dependency-name: 'typescript'
      - dependency-name: 'react'
      - dependency-name: 'react-native'
      - dependency-name: 'react-dom'
      - dependency-name: 'jest-expo'
      - dependency-name: 'jest'
      - dependency-name: '@jest/globals'
      - dependency-name: '@babel/core'
      - dependency-name: 'sentry-expo'
      - dependency-name: 'react-native-web'
      - dependency-name: 'react-native-svg'
      - dependency-name: 'react-native-safe-area-context'
      - dependency-name: '@react-native-async-storage/async-storage'
      - dependency-name: 'react-native-screens'
      - dependency-name: 'expo-camera'
      - dependency-name: 'expo-device'
      - dependency-name: 'expo-font'
      - dependency-name: 'expo-linking'
      - dependency-name: 'expo-updates'
      - dependency-name: 'expo-constants'
      - dependency-name: 'expo-dev-client'
      - dependency-name: 'expo-web-browser'
      - dependency-name: 'expo-application'
      - dependency-name: 'expo-asset'
      - dependency-name: 'expo-permissions'
      - dependency-name: 'expo-splash-screen'
      - dependency-name: 'expo-status-bar'
      - dependency-name: 'expo-store-review'
      - dependency-name: '@types/react'
      - dependency-name: '@types/react-native'
