name: OTA-Production - trigger OTA-update-workflow with target environment 'production'

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: hackberrybay/hackberry-expo/.github/workflows/ota-update.yml@main
    with:
      target_environment: production
      api_host: https://playground.devskills.co/
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
