name: OTA-Update - publish js update to target environment, publishes to both platforms

on:
  workflow_call:
    inputs:
      target_environment:
        required: true
        type: string
      api_host:
        required: true
        type: string
    secrets:
      EXPO_TOKEN:
        required: true

jobs:
  expo-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      API_HOST: ${{ inputs.api_host }}
      EXPO_BUILD_ENV: ${{ inputs.target_environment }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Set processed environment variable
        run: echo "GIT_COMMIT_SHA=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Run tests
        run: |
          yarn jest --ci

      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: expo publish --release-channel ${{ inputs.target_environment }}
