name: Review Dog
on: [pull_request]
jobs:
  eslint:
    name: Sniffing Code
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
