name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Check for TypeScript errors
        run: |
          npx tsc --noEmit
      - name: Run tests
        run: |
          yarn jest --ci
